# Generated by Django 3.0.2 on 2020-02-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_list',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='like_num',
            field=models.SmallIntegerField(default=0),
        ),
    ]
