# Generated by Django 3.0.2 on 2020-02-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20200219_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_num',
            field=models.SmallIntegerField(default=0),
        ),
    ]
